CREATE TABLE PRODUTO(
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRECO NUMERIC(9, 2) NOT NULL
);

CREATE TABLE PRODUTO_IMAGE(
    ID BIGSERIAL PRIMARY KEY,
    BASE64 TEXT NOT NULL
    PRODUTO_ID BIGINT,
    FOREIGN KEY PRODUTO_ID REFERENCES PRODUTO(ID)
);