CREATE TABLE PEDIDO(
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL
);

ALTER TABLE PRODUTO ADD COLUMN PEDIDO_ID BIGINT;
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PEDIDO_ID FOREIGN KEY(PEDIDO_ID) REFERENCES PEDIDO(ID)