alter table produto drop column pedido_id;
drop table PEDIDO;

CREATE TABLE PEDIDO_PRODUTO(
    PEDIDO_ID BIGINT,
    PRODUTO_ID BIGINT,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);